/**
 * Moltbook API Client
 * Used to interface the TRADING AI Agent (Antigravity) with the Moltbook Autonomous Social Network.
 */

const MOLTBOOK_BASE = 'https://moltbook.com/api/v1';

let moltbookPostsToday = 0;
let lastMoltbookPost: string | null = null;

export function getMoltbookTelemetry() {
  return {
    postsToday: moltbookPostsToday,
    lastPost: lastMoltbookPost,
  };
}

async function fetchMoltbook(endpoint: string, options: RequestInit = {}) {
  const apiKey = process.env.MOLTBOOK_API_KEY;
  if (!apiKey) {
    throw new Error('MOLTBOOK_API_KEY environment variable is not set');
  }

  const res = await fetch(`${MOLTBOOK_BASE}${endpoint}`, {
    ...options,
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  if (!res.ok) {
    let errText = await res.text().catch(() => 'Unknown error');
    try {
      const parsed = JSON.parse(errText);
      errText = parsed.message || JSON.stringify(parsed);
    } catch {
      // Keep original text
    }
    throw new Error(`Moltbook API Error [${res.status}]: ${errText}`);
  }

  return res.json();
}

/**
 * Validates the agent identity and connection health.
 */
export async function getAgentIdentity() {
  return fetchMoltbook('/agents/me');
}

/**
 * Fetches the personalized feed for the agent (incorporating trending posts & timeline).
 */
export async function fetchHomeFeed(limit = 20) {
  return fetchMoltbook(`/home?limit=${limit}`);
}

/**
 * Posts an insight or insight generated by this agent onto the platform natively.
 */
export async function postActivity(content: string, replyToId?: string, submoltStr: string = "crypto") {
  const payload: Record<string, unknown> = { 
    content,
    title: content.substring(0, 50) + "...",
    submolt: submoltStr,
    submolt_name: submoltStr
  };
  if (replyToId) {
    payload.reply_to_id = replyToId;
  }
  const response = await fetchMoltbook('/posts', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
  
  if (response) {
      moltbookPostsToday++;
      lastMoltbookPost = new Date().toISOString();
  }
  
  return response;
}

/**
 * Validates a pending post by submitting the resolved math captchas.
 */
export async function verifyPost(verification_code: string, answer: string) {
  return fetchMoltbook('/verify', {
    method: 'POST',
    body: JSON.stringify({ verification_code, answer })
  });
}

/**
 * KARMA BUILDER v2 — Search endpoint wrapper.
 * Returns posts matching query; filter applied server-side on content + title.
 * NOTE: Moltbook's ?type=post filter is buggy (returns 0) — use default type.
 */
export interface MoltbookSearchResult {
  id: string;
  type: 'post' | 'comment' | 'agent' | 'submolt';
  title: string | null;
  content: string | null;
  upvotes: number;
  downvotes: number;
  created_at: string;
  author: { id: string; name: string } | null;
  submolt: { id: string; name: string; display_name: string } | null;
  post_id: string;
}

export async function searchPosts(query: string, limit = 10): Promise<MoltbookSearchResult[]> {
  const encoded = encodeURIComponent(query);
  const res = await fetchMoltbook(`/search?q=${encoded}&limit=${limit}`);
  const results: MoltbookSearchResult[] = (res?.results || []).filter((r: MoltbookSearchResult) => r.type === 'post');
  return results;
}

/**
 * Fetch comments on a post (used to avoid replying twice to same thread).
 */
export async function fetchPostComments(postId: string, limit = 20) {
  return fetchMoltbook(`/posts/${postId}/comments?sort=new&limit=${limit}`);
}
