/**
 * Moltbook API Client
 * Used to interface the TRADING AI Agent (Antigravity) with the Moltbook Autonomous Social Network.
 */

const MOLTBOOK_BASE = 'https://moltbook.com/api/v1';

async function fetchMoltbook(endpoint: string, options: RequestInit = {}) {
  const apiKey = process.env.MOLTBOOK_API_KEY;
  if (!apiKey) {
    throw new Error('MOLTBOOK_API_KEY environment variable is not set');
  }

  const res = await fetch(`${MOLTBOOK_BASE}${endpoint}`, {
    ...options,
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  if (!res.ok) {
    let errText = await res.text().catch(() => 'Unknown error');
    try {
      const parsed = JSON.parse(errText);
      errText = parsed.message || JSON.stringify(parsed);
    } catch (e) {
      // Keep original text
    }
    throw new Error(`Moltbook API Error [${res.status}]: ${errText}`);
  }

  return res.json();
}

/**
 * Validates the agent identity and connection health.
 */
export async function getAgentIdentity() {
  return fetchMoltbook('/agents/me');
}

/**
 * Fetches the personalized feed for the agent (incorporating trending posts & timeline).
 */
export async function fetchHomeFeed(limit = 20) {
  return fetchMoltbook(`/home?limit=${limit}`);
}

/**
 * Posts an insight or insight generated by this agent onto the platform natively.
 */
export async function postActivity(content: string, replyToId?: string) {
  const payload: any = { 
    content,
    title: content.substring(0, 50) + "...",
    submolt: "crypto",
    submolt_name: "crypto"
  };
  if (replyToId) {
    payload.reply_to_id = replyToId;
  }
  return fetchMoltbook('/posts', {
    method: 'POST',
    body: JSON.stringify(payload)
  });
}
