-- ============================================================
-- FAZA 3.3 — Polymarket Decision Log (append-only)
-- Purpose: store per-opportunity evaluation with the full factor
-- decomposition (edge × goldsky × karma × liquidity) + rationale
-- for audit, replay, and learning loop (FAZA 3.6).
-- Generated: 2026-04-20
-- ============================================================

CREATE TABLE IF NOT EXISTS polymarket_decisions (
  id                BIGSERIAL   PRIMARY KEY,
  decision_id       TEXT        UNIQUE,              -- uuid generated by code
  gladiator_id      TEXT        NOT NULL,
  division          TEXT        NOT NULL,
  market_id         TEXT        NOT NULL,
  condition_id      TEXT,
  direction         TEXT        NOT NULL,            -- BUY_YES | BUY_NO | SKIP
  confidence        NUMERIC,                         -- 0-100
  edge_score        NUMERIC,                         -- 0-100 raw edge
  goldsky_confirm   NUMERIC,                         -- 0.5 - 1.5 multiplier
  moltbook_karma    NUMERIC,                         -- 0.5 - 1.5 multiplier
  liquidity_sanity  NUMERIC,                         -- 0 - 1 multiplier
  final_score       NUMERIC,                         -- product of the above
  acted             BOOLEAN     DEFAULT FALSE,       -- TRUE if phantom bet written
  skip_reason       TEXT,                            -- why action was skipped
  rationale         JSONB,                           -- array of {factor, value, note}
  raw_opportunity   JSONB,                           -- snapshot for replay
  decided_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poly_dec_decided_at ON polymarket_decisions(decided_at DESC);
CREATE INDEX IF NOT EXISTS idx_poly_dec_gladiator  ON polymarket_decisions(gladiator_id);
CREATE INDEX IF NOT EXISTS idx_poly_dec_market     ON polymarket_decisions(market_id);
CREATE INDEX IF NOT EXISTS idx_poly_dec_condition  ON polymarket_decisions(condition_id);
CREATE INDEX IF NOT EXISTS idx_poly_dec_acted      ON polymarket_decisions(acted) WHERE acted = TRUE;
