-- ============================================================
-- FAZA 3.4 — Polymarket Scan History + run linkage
-- Purpose: one row per cron scan tick with divisions scanned,
-- opportunities found, bets placed, duration, env snapshot.
-- Plus ALTER on polymarket_decisions to link each decision to
-- its run (run_id) — enables run-level drill-down in FAZA 3.5 UI.
-- Generated: 2026-04-20
-- ============================================================

-- 1. Scan history: append-only audit log
CREATE TABLE IF NOT EXISTS polymarket_scan_history (
  id                    BIGSERIAL   PRIMARY KEY,
  run_id                TEXT        UNIQUE,                -- uuid generated by code
  started_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at           TIMESTAMPTZ,                        -- NULL until finishScanRun
  duration_ms           INT,
  divisions_scanned     JSONB,                              -- string[]
  opportunities_found   INT         DEFAULT 0,
  bets_placed           INT         DEFAULT 0,
  decisions_logged      INT         DEFAULT 0,              -- total correlateDecision rows
  correlation_disabled  BOOLEAN     DEFAULT FALSE,          -- POLYMARKET_CORRELATION_ENABLED=0
  errors                JSONB,                              -- array of {division, error}
  env_snapshot          JSONB,                              -- thresholds at run time
  created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_poly_sh_started  ON polymarket_scan_history(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_poly_sh_run_id   ON polymarket_scan_history(run_id);

-- 2. Link decisions to their scan run (idempotent)
ALTER TABLE polymarket_decisions
  ADD COLUMN IF NOT EXISTS run_id TEXT;

CREATE INDEX IF NOT EXISTS idx_poly_dec_run_id  ON polymarket_decisions(run_id);
